virtuel/prospect/urls.py
from django.urls import path
from . import views
app_name = "prospect"
urlpatterns = [
    path("", views.index, name="index"),
    path("prospecting", views.prospecting, name="prospecting"),
    path("clients", views.clients, name="clients"),
    path("agents", views.agents, name="agents"),
    path("saved", views.saved, name="saved"),
    path("seen", views.seen, name="seen"),
    path("marketing", views.marketing, name="marketing")

]

virtuel/virtuel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Home/', include('prospect.urls', namespace='prospect'))
]

virtuel/prospect/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class Agent(models.Model):
    name = models.CharField(max_length=20)
    phone = PhoneNumberField(null=True, blank=True, unique=True)
    email = models.CharField(max_length=60, blank=True, null=True)
    contacted = models.BooleanField(default=False)
    client = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Listing(models.Model):
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE)
    address = models.CharField(max_length=95)
    sc = models.SmallIntegerField(default=0)
    cb = models.SmallIntegerField(default=0)
    lowInterest = 'LI'
    medInterest = 'MI'
    highInterest = 'HI'
    interest_choices = [
        (lowInterest, 'Low Interest'),
        (medInterest, 'Medium Interest'),
        (highInterest, 'High Interest'),

    ]
    interested = models.CharField(
        max_length=2, choices=interest_choices, default=medInterest)
    comments = models.CharField(max_length=500, blank=True, null=True)
    saved = models.BooleanField(default=False)
    seen = models.BooleanField(default=False)

    def __str__(self):
        return self.address

virtuel/prospect/views.py
from django.shortcuts import render
from django.db import models
from django.http import HttpResponseRedirect
from prospect.models import Agent, Listing
from django.core.paginator import Paginator


def index(request):
    return render(request, "prospect/index.html")


def marketing(request):
    return render(request, "prospect/marketing.html")


def clients(request):
    return render(request, "prospect/clients.html")


def agents(request):
    return render(request, "prospect/agents.html")


def saved(request):
    return render(request, "prospect/saved.html")


def seen(request):
    return render(request, "prospect/seen.html")


def prospecting(request):
    listing = Listing.objects.all().filter(seen=False)
    paginator = Paginator(listing, 1)
    page_number = request.GET.get('page')
    listing_obj = paginator.get_page(page_number)
    return render(request, "prospect/prospect.html", {
        'listings': listing_obj
    })

virtuel/prospect/templates/prospect/agents.html
{% extends "prospect/layout.html" %} {% block body %}
<h1>Agents</h1>
{% endblock %}

virtuel/prospect/templates/prospect/clients.html
{% extends "prospect/layout.html" %} {% block body %}
<h1>Clients</h1>
{% endblock %}

virtuel/prospect/templates/prospect/index copy.html
{% extends "prospect/layout.html" %}



{% block body %}
{% for listing in listings %}
        {% if listing.agent.contacted == False %}
            <div class="alert alert-success" role="alert">
            Agent Never been Contacted!
            </div>
        {% else %}
            <div class="alert alert-danger" role="alert">
            Agent has been contacted before!
            </div>
        {% endif %}
    <h1>{{listing.agent.name}}</h1>
    <h3>{{listing.address}}</h3>
    <h3>{{listing.agent.phone}}</h3>
{% endfor %}

    <ul class='pagination'>
        {% if listings.has_previous %}
        <li class='page-item'>
            <a href="?page=1" class='page-link'>First</a>
        </li>
        <li><a href="{{listings.previous_page_link}}" class='page-link'>Previous</a></li>
        {% endif %}
        {% if listings.has_next %}
        <li class='page-item'>
            <a href="?page={{listings.next_page_number}}" class='page-link'>Next</a>
        </li>
        
        {% endif %}
    </ul>
{% endblock %}

    

virtuel/prospect/templates/prospect/index.html
{% extends "prospect/layout.html" %}



{% block body %}
    <h1>HOME</h1>
{% endblock %}

    

virtuel/prospect/templates/prospect/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Prospect</title>
    <link rel="stylesheet" type="text/css" href="{% static 'prospect/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'prospect/prospect.css' %}">
    <script src="{% static 'prospect/script.js' %}"></script>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>

</head>

<body>
    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="{% url 'prospect:index' %}">Dashboard</a>
        <a href="{% url 'prospect:prospecting' %}">Prospecting</a>
        <a href="{% url 'prospect:marketing' %}">Marketing</a>
        <a href="{% url 'prospect:clients' %}">Clients</a>
        <a href="{% url 'prospect:agents' %}">Agents</a>
        <a href="{% url 'prospect:saved' %}">Saved</a>
        <a href="{% url 'prospect:seen' %}">Seen</a>
    </div>

    <!-- Use any element to open the sidenav -->
    <div class="menu-container" onclick="openNav()">
        <div class="bar1"></div>
        <div class="bar2"></div>
        <div class="bar3"></div>
    </div>

    <!-- Add all page content inside this div if you want the side nav to push page content to the right (not used if you only want the sidenav to sit on top of the page -->
    <div id="main">
        {% block body %}
        {% endblock %}
    </div>

</body>

</html>

virtuel/prospect/templates/prospect/marketing.html
{% extends "prospect/layout.html" %} {% block body %}
<h1>Marketing</h1>
{% endblock %}

virtuel/prospect/templates/prospect/oldlayout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Prospect</title>
    <link rel="stylesheet" type="text/css" href="{% static 'prospect/style.css' %}">
    <script src="{% static 'prospect/script.js' %}"></script>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>

</head>

<body>
    <div id="con" class="alert alert-success" role="alert">
        Agent Never been Contacted!
    </div>
    <div id="co" class="alert alert-danger" role="alert">
        Agent has been contacted before!
    </div>
    <div class="d-flex" id="wrapper">

        <div class="bg-cus border-right" id="sidebar-wrapper">
            <div id='mh' class="sidebar-heading">VIRTUE DESIGN</div>
            <div class="list-group list-group-flush">
                <a href="{% url 'prospect:index' %}" class="list-group-item list-group-item-action">Dashboard</a>
                <a href="{% url 'prospect:prospecting' %}"
                    class="list-group-item list-group-item-action">Prospecting</a>
                <a href="{% url 'prospect:marketing' %}" class="list-group-item list-group-item-action">Marketing</a>
                <a href="{% url 'prospect:clients' %}" class="list-group-item list-group-item-action">Clients</a>
                <a href="{% url 'prospect:agents' %}" class="list-group-item list-group-item-action">Agents</a>
                <a href="{% url 'prospect:saved' %}" class="list-group-item list-group-item-action">Saved</a>
                <a href="{% url 'prospect:seen' %}" class="list-group-item list-group-item-action">Seen</a>
            </div>
        </div>
        <div class="page-content">
            {% block body %}
            {% endblock %}
        </div>

    </div>

</body>

</html>

virtuel/prospect/templates/prospect/prospect.html
{% extends "prospect/layout.html" %}
<div id="page-container">
    {% block body %}
        <div id="content-wrap">
            {% for listing in listings %}
                {% if listing.agent.contacted == False %}
                    <div id="con" class="alert alert-success" role="alert">
                        Agent Never been Contacted!
                    </div>
                {% else %}
                    <div id="co" class="alert alert-danger" role="alert">
                        Agent has been contacted before!
                    </div>
                {% endif %}
                <div id="name">
                    <h1 id="agent_name">{{listing.agent.name}}</h1>
                </div>
                <h3 id="listing_address">{{listing.address}}</h3>
                <br></br>
                <div class="flex-card-container">
                    
                    <div class="flexcard-content">
                        {% if listing.cb == 0 %}
                            <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
                                <div id="cbt" class="card-header">Contacted Before</div>
                                <div class="card-body">
                                    <h5 class="card-title">{{listing.cb}}</h5>
                                </div>
                                
                            </div>
                        {% else %}
                            <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
                                <div class="card-header">Contacted Before</div>
                                <div class="card-body">
                                    <h5 class="card-title">{{listing.cb}}</h5>
                                </div>
                                
                            </div>
                        {% endif %}
                    </div>
                    <div class="flexcard-content">
                        {% if listing.interested == "MI" %}
                            <div class="card text-white bg-warning mb-3" style="max-width: 18rem;">
                                <div class="card-header">Interest</div>
                                <div class="card-body">
                                    <h5 class="card-title">{{listing.interested}}</h5>
                                </div>
                                
                            </div>
                        {% elif listing.interested == "HI" %}
                            <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
                                <div class="card-header">Contacted Before</div>
                                <div class="card-body">
                                    <h5 class="card-title">{{listing.interested}}</h5>
                                </div>
                                
                            </div>
                        {% elif listing.interested == "LI" %}
                            <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
                                <div class="card-header">Contacted Before</div>
                                <div class="card-body">
                                    <h5 class="card-title">{{listing.interested}}</h5>
                                </div>
                                
                            </div>
                        {% endif %}
                    </div>
                    <div class="flexcard-content">
                        {% if listing.sc == 0 %}
                            <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
                                <div id="scbt" class="card-header">Successfully Contacted Before</div>
                                <div class="card-body">
                                    <h5 class="card-title">{{listing.sc}}</h5>
                                </div>
                                
                            </div>
                        {% else %}
                            <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
                                <div class="card-header">Successfully Contacted Before</div>
                                <div class="card-body">
                                    <h5 class="card-title">{{listing.sc}}</h5>
                                </div>
                                
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div id="edit">
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dropdown button
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                </div>
                <div id="footer">
                    <div class="footer-container">
                        <div class="footer-flex-content">
                            <button id="footer-call" class="btn btn-warning"><a id="save">Save</a></button>
                        </div>
                        <div class="footer-flex-content">
                            <button id="footer-call" class="btn btn-success"><a id="call-agent" href="tel:{{listing.agent.phone}}">Call</a></button>
                        </div>
                        <div class="footer-flex-content" id="pagination">
                            <ul class='pagination'>
                                {% if listings.has_previous %}
                                <li class='page-item'>
                                    <a href="?page=1" class='page-link'>First</a>
                                </li>
                                <li><a href="{{listings.previous_page_link}}" class='page-link'>Previous</a></li>
                                {% endif %}
                                {% if listings.has_next %}
                                <li class='page-item'>
                                    <a href="?page={{listings.next_page_number}}" class='page-link'>Next</a>
                                </li>

                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
                
            {% endfor %}
        </div>

        
    {% endblock %}
</div>

virtuel/prospect/templates/prospect/saved.html
{% extends "prospect/layout.html" %} {% block body %}
<h1>Saved</h1>
{% endblock %}

virtuel/prospect/templates/prospect/seen.html
{% extends "prospect/layout.html" %} {% block body %}
<h1>Seen</h1>
{% endblock %}